### ISSUE TITLE
forms to allowing inputs

### ISSUE THREAD

**Issue by marksikaundi** [marksikaundi/Signal-2022#1]
error codes
`  at http://192.168.8.101:19006/static/js/bundle.js:92970:25
    at NativeSafeAreaView (http://192.168.8.101:19006/static/js/bundle.js:83965:23)
    at SafeAreaProvider (http://192.168.8.101:19006/static/js/bundle.js:84147:24)
    at SafeAreaProviderCompat (http://192.168.8.101:19006/static/js/bundle.js:13652:23)
    at NativeStackView (http://192.168.8.101:19006/static/js/bundle.js:14049:20)
    at NativeStackNavigator (http://192.168.8.101:19006/static/js/bundle.js:13986:31)
    at EnsureSingleNavigator (http://192.168.8.101:19006/static/js/bundle.js:8548:23)
    at BaseNavigationContainer (http://192.168.8.101:19006/static/js/bundle.js:8181:27)
    at ThemeProvider (http://192.168.8.101:19006/static/js/bundle.js:14675:20)
    at NavigationContainerInner (http://192.168.8.101:19006/static/js/bundle.js:14314:25)
    at App
    at ExpoRootComponent (http://192.168.8.101:19006/static/js/bundle.js:22251:83)
    at div
    at http://192.168.8.101:19006/static/js/bundle.js:92970:25
    at div
    at http://192.168.8.101:19006/static/js/bundle.js:92970:25
    at AppContainer (http://192.168.8.101:19006/static/js/bundle.js:84891:24)`

**Comment by marksikaundi** [comment]
solved `Input`
